# Ptwist Network

Organizations:

    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: crypto-config/ordererOrganizations/example.com/msp

    - &MEDSOS
        Name: MEDSOSMSP
        ID: MEDSOSMSP
        MSPDir: crypto-config/peerOrganizations/MEDSOS.example.com/msp
        AnchorPeers:
            - Host: peer0.MEDSOS.example.com
              Port: 7051

Orderer: &OrdererDefaults

    OrdererType: kafka
    Addresses:
        - orderer0:7050
    BatchTimeout: 1s
    BatchSize:
        MaxMessageCount: 30
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Kafka:
        Brokers:
            - kafka0:9092
    Organizations:
    
Application: &ApplicationDefaults
    Organizations:

Profiles:

    OneOrgOrdererGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *MEDSOS
    OneOrgChannel:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *MEDSOS

